# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakgi', models.SmallIntegerField(verbose_name='hakgi')),
                ('hakno', models.CharField(max_length=10, verbose_name='hakno')),
                ('bb', models.CharField(max_length=2, verbose_name='bb')),
                ('sbb', models.CharField(max_length=2, verbose_name='sbb')),
                ('title', models.CharField(default='', max_length=20, verbose_name='title')),
                ('room', models.CharField(max_length=10, verbose_name='room')),
                ('max_student', models.SmallIntegerField(verbose_name='max_student')),
                ('participation', models.SmallIntegerField(verbose_name='participation')),
                ('min_mile', models.SmallIntegerField(verbose_name='min_mile')),
                ('max_mile', models.SmallIntegerField(verbose_name='max_mile')),
                ('avr_mile', models.SmallIntegerField(verbose_name='avr_mile')),
                ('professor', models.CharField(max_length=10, verbose_name='prof')),
                ('credit', models.SmallIntegerField(verbose_name='credit')),
                ('analysis', models.BooleanField(verbose_name='isAnalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('password', models.CharField(max_length=10, verbose_name='pass')),
                ('is_active', models.BooleanField(verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='MileResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(verbose_name='rank')),
                ('mileage', models.SmallIntegerField(verbose_name='mileage')),
                ('isMajor', models.BooleanField(verbose_name='isMajor')),
                ('numEnroll', models.SmallIntegerField(verbose_name='numEnroll')),
                ('graduation', models.BooleanField(verbose_name='isMajor')),
                ('first', models.BooleanField(verbose_name='first')),
                ('credit', models.SmallIntegerField(verbose_name='mileage')),
                ('prev', models.FloatField(verbose_name='prev')),
                ('grade', models.SmallIntegerField(verbose_name='grade')),
                ('result', models.BooleanField(verbose_name='result')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yonto.Course')),
            ],
        ),
    ]
